# Generated by Django 6.0.3 on 2026-04-09 09:08

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/defaults/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), core.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
