# Generated by Django 6.0.3 on 2026-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Yêu cầu kỹ năng'),
        ),
    ]
