# Generated by Django 6.0.3 on 2026-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả công ty'),
        ),
    ]
