# Generated by Django 6.0.3 on 2026-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kinh nghiệm'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hình thức làm việc'),
        ),
        migrations.AddField(
            model_name='job',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng tuyển'),
        ),
    ]
