# Generated by Django 6.0.3 on 2026-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job_experience_job_job_type_job_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Không yêu cầu', 'Không yêu cầu'), ('Thực tập / Fresher', 'Thực tập / Fresher'), ('1 - 3 năm', '1 - 3 năm'), ('Trên 3 năm', 'Trên 3 năm')], default='Không yêu cầu', max_length=100, verbose_name='Kinh nghiệm'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Toàn thời gian', 'Toàn thời gian'), ('Bán thời gian', 'Bán thời gian'), ('Làm từ xa', 'Làm từ xa')], default='Toàn thời gian', max_length=100, verbose_name='Hình thức làm việc'),
        ),
    ]
