# Generated by Django 6.0.3 on 2026-04-12 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_job_experience_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('none', 'Không yêu cầu'), ('0_1', 'Dưới 1 năm'), ('1_3', '1 - 3 năm'), ('3_5', '3 - 5 năm'), ('over_5', 'Trên 5 năm')], default='none', max_length=50, verbose_name='Kinh nghiệm'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Toàn thời gian'), ('part_time', 'Bán thời gian'), ('remote', 'Làm từ xa'), ('hybrid', 'Hybrid (Kết hợp)')], default='full_time', max_length=50, verbose_name='Hình thức làm việc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng tuyển'),
        ),
    ]
