# Generated by Django 6.0.3 on 2026-04-21 06:43

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ công ty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_cv',
            field=models.FileField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to=core.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), core.models.validate_file_size]),
        ),
    ]
