# Generated by Django 6.0.3 on 2026-05-02 12:46

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_address_alter_user_default_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), core.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CV Không Tên', max_length=200)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('target_major', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí ứng tuyển')),
                ('objective', models.TextField(blank=True, null=True, verbose_name='Mục tiêu nghề nghiệp')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='cv_avatars/')),
                ('education', models.JSONField(blank=True, default=list, null=True)),
                ('experience', models.JSONField(blank=True, default=list, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('projects', models.JSONField(blank=True, default=list, null=True)),
                ('certifications', models.JSONField(blank=True, default=list, null=True)),
                ('template_name', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='online_cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.cv'),
        ),
    ]
