# Generated by Django 6.0.3 on 2026-05-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_application_cv_file_cv_application_online_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
