# Generated by Django 6.0.3 on 2026-05-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cv_github_cv_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('skill_score', models.IntegerField(default=0)),
                ('exp_score', models.IntegerField(default=0)),
                ('desc_score', models.IntegerField(default=0)),
                ('project_score', models.IntegerField(default=0)),
                ('bonus_score', models.IntegerField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('matched_keywords', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('interview_questions', models.JSONField(blank=True, default=list, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='core.application')),
            ],
        ),
    ]
