# Generated by Codex on 2026-05-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_applicationmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Chờ duyệt'),
                    ('Viewed', 'Đã xem'),
                    ('Interview', 'Mời phỏng vấn'),
                    ('Accepted', 'Chấp nhận'),
                    ('Rejected', 'Từ chối'),
                ],
                db_index=True,
                default='Pending',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Tại văn phòng'), ('phone', 'Gọi điện')], default='online', max_length=20)),
                ('location', models.CharField(max_length=500, verbose_name='Link hoặc địa điểm phỏng vấn')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='core.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
